import Head from "next/head";
import type { NextPage } from "next";
import axios from "axios";
import { Video } from "../utils/types";
import { VideoCard, NoResults } from "../components";
import { BASE_URL } from "../utils";

interface IProps {
	videos: Video[];
}

const Home: NextPage<IProps> = ({ videos }) => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex flex-col h-full gap-10 videos">
				{videos.length ? (
					videos.map((video) => <VideoCard post={video} key={video._id} />)
				) : (
					<NoResults text="No Videos" />
				)}
			</div>
		</div>
	);
};

export const getServerSideProps = async ({
	query: { topic },
}: {
	query: { topic: string };
}) => {
	let response = null;

	if (topic) {
		response = await axios.get(`${BASE_URL}/api/discover/${topic}`);
	} else {
		response = await axios.get(`${BASE_URL}/api/post`);
	}

	return {
		props: {
			videos: response.data,
		},
	};
};

export default Home;
